name: de-sar-sample-data
channels:
- conda-forge
- nodefaults
dependencies:
- proj >=9.5.1
- netcdf4 >=1.7.2
- python >=3.10,<3.14
- pip
- pip:
  - -e .
  - dea-tools>=0.4.10
  - asf-search>=12.2.2
  - ipykernel>=6.3.1
  - ipywidgets>=8.1.7
  - stac-geoparquet>=0.8.0
  - matplotlib>=3.10, <3.11
  - xarray>=2025.6.1
  - pystac>=1.14.1
  - numpy>=2.2.6, <3
  - scikit-image>=0.25.2
  - odc-geo>=0.5.0
  - pystac-client>=0.9.0
  - odc-stac>=0.4.0
  - scipy>=1.14.1
