[build-system]
requires = ["setuptools>=61.0", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[project]
name = "de-sar-demo"
requires-python = ">=3.10,<3.14"
authors = [
    {name="Geoscience Australia", email="DigitalEarthAntarctica@ga.gov.au"},
]
description = "Geoscience Australia SAR Backscatter Demo"
version = "0.0.1"
dependencies = [
    "dea-tools>=0.4.10", 
    "asf-search>=12.2.2", 
    "ipykernel>=6.3.1", 
    "ipywidgets>=8.1.7", 
    "stac-geoparquet>=0.8.0", 
    "matplotlib>=3.10,<3.11",
    "xarray>=2025.6.1",
    "pystac>=1.14.1", 
    "numpy>=2.2.6,<3", 
    "scikit-image>=0.25.2",
    "odc-geo>=0.5.0",
    "pystac-client>=0.9.0",
    "odc-stac>=0.4.0",
    "scipy>=1.14.1",
]

[tool.setuptools.packages.find]
where = ["."]

[project.urls]
Homepage = "https://github.com/caitlinadams/de-sar-sample-data.git"

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]

[tool.pixi.pypi-dependencies]
de-sar-demo = { path = ".", editable = true }

[tool.pixi.dependencies]
proj = ">=9.5.1"
netcdf4 = ">=1.7.2"

[tool.pixi.environments]
default = { solve-group = "default" }

[tool.pixi.tasks]
export-conda = """
pixi workspace export conda-environment -e default environment.yaml && \
sed -ix "s/^name: default$/name: de-sar-sample-data/" environment.yaml; rm environment.yamlx
"""
export-requirements = """
uv pip compile pyproject.toml -o requirements.txt
"""
